local ServerAuthToolkit = require("@self/src")

export type MovementState = ServerAuthToolkit.MovementState
export type MovementModuleDefinition = ServerAuthToolkit.MovementModuleDefinition
export type AnimationSettings = ServerAuthToolkit.AnimationSettings
export type PreCameraSimulationEntry = ServerAuthToolkit.PreCameraSimulationEntry
export type PostCameraVisualEntry = ServerAuthToolkit.PostCameraVisualEntry
export type ServerAuthToolkit = ServerAuthToolkit.ServerAuthToolkit

return ServerAuthToolkit
