[package]
name = "cameronnh/serverauthtoolkit"
version = "0.1.4"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
include = ["default.project.json", "LICENSE", "src", "init.luau"]
exclude = [
	".github",
	".vscode",
	"build",
	"moonwave.toml",
	"scripts",
	"README.md",
	"sourcemap.json"
]

[dependencies]
