[package]
name = "cameronnh/serverauthtoolkit"
version = "0.1.7"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	".github",
	".vscode",
	"build",
	"moonwave.toml",
	"scripts",
	"README.md",
	"sourcemap.json",
	"stylua.toml",
	"rokit.toml"
]

[dependencies]
